version: "3"
services:
    django_daphne:
        container_name: django_daphne
        build:
            context: ./
        volumes:
            - ./backend/pathshare/staticfiles:/app/backend/pathshare/staticfiles
        ports:
            - "8000:8000"
        depends_on:
            - db

    react_nginx:
        container_name: react_nginx
        build:
            context: ./frontend
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./backend/pathshare/staticfiles:/staticfiles
        depends_on:
            - django_daphne

    db:
        container_name: db
        image: postgres:latest
        environment:
            POSTGRES_DB: pathshare
            POSTGRES_USER: jhemin0415
            POSTGRES_PASSWORD: djdkdl159
