version: "3"
services:
    django_app:
        container_name: django_app
        build:
            context: ./
        volumes:
            - ./backend/pathshare/staticfiles:/app/backend/pathshare/staticfiles
        ports:
            - "8000:8000"
        depends_on:
            - db

    nginx_with_certbot:
        container_name: nginx_with_certbot
        build:
            context: ./nginx
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./backend/pathshare/staticfiles:/staticfiles
        depends_on:
            - django_app

    db:
        container_name: db
        image: postgres:latest
        environment:
            POSTGRES_DB: pathshare
            POSTGRES_USER: jhemin0415
            POSTGRES_PASSWORD: djdkdl159
